#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Emanci\MysqlDiffFixer\Application;

$config = include __DIR__.'/config/config.php';
$application = new Application($config);
$application->run();
